# Generated by Django 6.1.1 on 2026-10-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_populate_faculty_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=50)),
                ('places', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
