# Generated by Django 6.1.1 on 2026-10-06 19:32

from django.db import migrations


EXCHANGE_SQL = """
INSERT INTO faculty_exchangeprogram
    (university, languages, places, deadline, description)
VALUES
    ('Uniwersytet Warszawski, Польща', 'польська, англійська', '5', '2026-11-15',
     'Найбільший університет Польщі з широким вибором курсів із соціальних наук. Частина дисциплін викладається англійською мовою.'),
    ('KU Leuven (Бельгія)', 'English', '2 місця', '2026-12-01',
     'Один із найстаріших університетів Європи, заснований у 1425 році. Студенти обміну навчаються англійською на курсах із соціальних і політичних наук.'),
    ('Vilnius University, Литва', 'англійська', 'до 4', '2026-10-20',
     'Найстаріший університет Литви, заснований у 1579 році. Пропонує курси англійською з політології та міжнародних відносин.'),
    ('Uniwersytet Jagielloński, Польща', 'Польська, Англійська', '3', '2026-11-15',
     'Найстаріший університет Польщі, заснований у 1364 році в Кракові. Студенти можуть обирати курси польською та англійською мовами.'),
    ('University of Tartu - Естонія', 'англійська, естонська', '2', '2027-01-10',
     'Провідний класичний університет Естонії, заснований у 1632 році. Програма обміну включає курси із соціальних наук англійською мовою.'),
    ('Masaryk University, Чехія', 'англійська', '1 місце', '2026-09-30',
     'Другий за величиною університет Чехії, розташований у Брно. Факультет соціальних студій пропонує курси англійською мовою.');
"""


REVERSE_SQL = """
DELETE FROM faculty_exchangeprogram
WHERE university IN (
    'Uniwersytet Warszawski, Польща',
    'KU Leuven (Бельгія)',
    'KU Leuven, Бельгія',
    'Vilnius University, Литва',
    'Uniwersytet Jagielloński, Польща',
    'University of Tartu - Естонія',
    'University of Tartu, Естонія',
    'Masaryk University, Чехія'
);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_exchangeprogram'),
    ]

    operations = [
        migrations.RunSQL(EXCHANGE_SQL, reverse_sql=REVERSE_SQL),
    ]
