# Generated by Django 6.1.1 on 2026-10-06 19:57

from django.db import migrations, models
def split_university(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        value = program.university.strip()

        if value.endswith(')') and ' (' in value:
            name, country = value.rsplit(' (', 1)
            country = country.rstrip(')')
        elif ' - ' in value:
            name, country = value.rsplit(' - ', 1)
        elif ', ' in value:
            name, country = value.rsplit(', ', 1)
        else:
            raise ValueError(f'Не вдалося розділити університет і країну: {value!r}')

        program.university_name = name.strip()
        program.country = country.strip()
        program.save(update_fields=['university_name', 'country'])

def join_university(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        program.university = f'{program.university_name}, {program.country}'
        program.save(update_fields=['university'])





class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_import_exchange_programs'),
    ]

    operations = [
    migrations.AddField(
        model_name='exchangeprogram',
        name='university_name',
        field=models.CharField(default='', max_length=100),
    ),
    migrations.AddField(
        model_name='exchangeprogram',
        name='country',
        field=models.CharField(default='', max_length=50),
    ),
    migrations.RunPython(split_university, join_university),
    migrations.AlterField(
        model_name='exchangeprogram',
        name='university',
        field=models.CharField(blank=True, max_length=100),
    ),
    migrations.RemoveField(
        model_name='exchangeprogram',
        name='university',
    ),
]
