# Generated by Django 6.1.1 on 2026-10-06 20:17
import re

from django.db import migrations, models


def places_to_number(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        match = re.search(r'\d+', program.places)
        if match is None:
            raise ValueError(f'Не вдалося знайти число в кількості місць: {program.places!r}')
       
        program.places_count = int(match.group())
        program.save(update_fields=['places_count'])


def places_to_text(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        program.places = str(program.places_count)
        program.save(update_fields=['places'])


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_split_university'),
    ]

    operations = [

        migrations.AddField(
            model_name='exchangeprogram',
            name='places_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(places_to_number, places_to_text),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='places',
        ),
        migrations.RenameField(
            model_name='exchangeprogram',
            old_name='places_count',
            new_name='places',
        ),
    ]
